### ISSUE TITLE
Committing changes triggers a bunch of NBFormatErrors.

### ISSUE THREAD

**Issue by abegong** [toobaz/ipynb_output_filter#5]
When I try to commit changes, I get a bunch of NBFormatErrors.

Looks like it might be a difference between version 4 and version 3...?

I'm a long-time python/git user, but pretty new to notebooks, so help would be much appreciated.

Here's the traceback:

```
$ git commit -am "added some changes..."
Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
[notebook-friendly Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
30d6221] added changes...
Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
Traceback (most recent call last):
  File "util/ipynb_output_filter.py", line 30, in <module>
    json_in = reads(to_parse, version)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
IPython.nbformat.current.NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
error: external filter util/ipynb_output_filter.py failed 1
error: external filter util/ipynb_output_filter.py failed
 2 files changed, 40 insertions(+), 6 deletions(-)
```

**Comment by RafalSkolasinski** [comment]
Could you tell me what version of IPython do you have? (output of `pip freeze` would be good) and which version of this script you have?

**Comment by toobaz** [comment]
@abegong please feel free to reopen and provide the info on Python version if you can still reproduce
